services:

  prolog-verification:
    env_file:
      - '../.env.local'
    build:
      context: '../'
      dockerfile: './etc/Dockerfile'
      args:
        - OWNER_UID=${PROGRAM_OWNER_UID:-1000}
        - OWNER_GID=${PROGRAM_OWNER_GID:-1000}
      tags:
        - "ghcr.io/revuedepresse/automated-theorem-proving-for-prolog-verification:base"
    labels:
      org.opencontainers.image.source: 'https://github.com/revuedepresse/automated-theorem-proving-for-prolog-verification'
    restart:  'always'
    platform: 'linux/amd64'
